// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgjq25zDVB2FChPGoLL4rEw9rtZ9bIIcI',
    appId: '1:1078399723536:web:51047c684bd32b96594295',
    messagingSenderId: '1078399723536',
    projectId: 'inventory-management-dat-b007d',
    authDomain: 'inventory-management-dat-b007d.firebaseapp.com',
    storageBucket: 'inventory-management-dat-b007d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_CC-e5FC1nT3n9btYLdcI6TOXkkSGQeU',
    appId: '1:1078399723536:android:7e690605051e30aa594295',
    messagingSenderId: '1078399723536',
    projectId: 'inventory-management-dat-b007d',
    storageBucket: 'inventory-management-dat-b007d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDswpFKIReHG-8tb4LC0gbNEy-TMe-6ijI',
    appId: '1:1078399723536:ios:4ab7ad9afeb728de594295',
    messagingSenderId: '1078399723536',
    projectId: 'inventory-management-dat-b007d',
    storageBucket: 'inventory-management-dat-b007d.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDswpFKIReHG-8tb4LC0gbNEy-TMe-6ijI',
    appId: '1:1078399723536:ios:4ab7ad9afeb728de594295',
    messagingSenderId: '1078399723536',
    projectId: 'inventory-management-dat-b007d',
    storageBucket: 'inventory-management-dat-b007d.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgjq25zDVB2FChPGoLL4rEw9rtZ9bIIcI',
    appId: '1:1078399723536:web:2021d12fc6192d6b594295',
    messagingSenderId: '1078399723536',
    projectId: 'inventory-management-dat-b007d',
    authDomain: 'inventory-management-dat-b007d.firebaseapp.com',
    storageBucket: 'inventory-management-dat-b007d.firebasestorage.app',
  );
}
